language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - cd csye6225-spring-boot-starter-webapp-master
  - ./gradlew war

notifications:
  email:
    recipients:
      - chandra.ra@husky.neu.edu
